### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by iihackerii** [xXxTheDarkprogramerxXx/PS3Tools#147]
Hi, First of all i love your PS2 GUI it’s fantastic and really nice work of you man I appreciate all of your efforts and daily updates  !! Well done
Note that im on the 27th update .
1- there is this bug that keeps happening all the time every time it keeps asking to re-download  emulators again and again... even though they are downloaded already :( Please fix it if possible 
2- jax v2 emu refuses to download it just crashes the application when you press download.
3- sometimes when making multiple iso’s it keeps saying Error on extracting resources it happens a lot almost all times🥺
4- Can you please add these emus if u can? 
(Rogue emu , kof98, starocean )

**Comment by xXxTheDarkprogramerxXx** [comment]
> Hi, First of all i love your PS2 GUI it’s fantastic and really nice work of you man I appreciate all of your efforts and daily updates !! Well done
> Note that im on the 27th update .
> 1- there is this bug that keeps happening all the time every time it keeps asking to re-download emulators again and again... even though they are downloaded already :( Please fix it if possible
> 2- jax v2 emu refuses to download it just crashes the application when you press download.
> 3- sometimes when making multiple iso’s it keeps saying Error on extracting resources it happens a lot almost all times🥺
> 4- Can you please add these emus if u can?
> (Rogue emu , kof98, starocean )

Good day thanks for the feedback 
1- There is a reason i keep asking you if you would like to redownload if i update one of the emulators (server side) you can simply redownload it if you say now you can continue to use it as normal (Just tested and this does work) 
2- I have been informed of the Jax v2 emu being a bit buggy and ill be looking into it over the weekend
3- This is something i will look into in a few moments as i didn't touch any code for multi iso since the 20th release i believe so its possible i screwed something else up (can confirm this is a bug just tested it seems the content id is not being generated correctly)
4- More emus will be added as time goes on if you want to see the full list of emu's that will be added you can grab the list here https://github.com/xXxTheDarkprogramerxXx/Ps2-Classics-emulators-for-Ps4
It should get updated as time goes on
I should have a new update out end of the month with about 4 new emulators to play with
Again thanks for the feedback

**Comment by xXxTheDarkprogramerxXx** [comment]
Good news found the issue with Multi Iso 
Thanks for the report it will be fixed in the next update for all users

**Comment by iihackerii** [comment]
awesome news < thank you very much

**Comment by denavis** [comment]
Friends, how to unpack PKG files after this program?
ORBIS issues passcode mismatch (all zeros are spelled out)
PS4PKGViewer.v1.5-LMAN throws Error While Extracting Files
PKGs are working, the games work flawlessly, but the weight is wrong, EXACTLY, they write.
I thought pkg the broken steel on my computer, I pull out the previously installed xplorer through ps4 xplorer, the same nonsense, I tried to convert it again through this program and the unpacking result is the same
maybe there are still some tools, albeit difficult to use?
I want to convert the images in Feng Shui.
You need to pull the PS2 images from the IMAGE / disc01.iso folder in each pkg
