### ISSUE TITLE
PS4PS2 Classics crash on startup

### ISSUE THREAD

**Issue by Abben86** [xXxTheDarkprogramerxXx/PS3Tools#31]
Hi. :)
Just downloaded this app to try it out, but when i open it closes instantly. I have tried running with and without admin rights, 7/8 compatibility. Nothing works :/ Do you have any clue whats wrong? Im running win10 64

**Comment by xXxTheDarkprogramerxXx** [comment]
Hi There,

Well to start did you first install the base application ? 

Regards

**Comment by xXxTheDarkprogramerxXx** [comment]
https://github.com/xXxTheDarkprogramerxXx/PS3Tools/releases/tag/PS2.1.0

**Comment by Abben86** [comment]
Yes, the base application is installed and runs just fine. Im just having problem with the latest version.

Thanks

**Comment by xXxTheDarkprogramerxXx** [comment]
Please give me a copy of the error your getting ? 

I would need that to try and reproduce the error.

else i would recommend a reinstall of the application might be that one of the settings got changed and are causing the issue ?

**Comment by Abben86** [comment]
I tried reinstalling the base app. Now when i download the latest release, should i place the debug folder somewhere or just run the application from inside that folder? And there is no error message, the app just automatically closes.

**Comment by xXxTheDarkprogramerxXx** [comment]
No need to do anything with the debug folder ?
You should be prompted by Windows for an up update and that should be all you need to do

**Comment by Abben86** [comment]
Anyway, the base app works and i have successfully create a PS2 pkg file and it worked on the PS4 :) Just a bummer that i cant get the latest release to work on my computer! Thanks for this awesome app by the way!

**Comment by xXxTheDarkprogramerxXx** [comment]
I'd really like to help you but I'm still confused about why you want to do anything with the debug folder can you post a small video somewhere like vimeo or onther platform so I can see what your doing from the start to the finish 
Even a reinstall that would be great so we can figure this out and have it working for more users

**Comment by Abben86** [comment]
https://youtu.be/YwifZQRiTvc

Base app and the latest release installation attempt. The video cuts out before i try to open the GUI.EXE, but it just shows a blank window then exits

Thanks.

**Comment by xXxTheDarkprogramerxXx** [comment]
I now know where your problem is 

You do not need to do anything with the debug folder.

once the base application is installed all you need to do is run the PS2 Classics Gui from your desktop 
![image](https://user-images.githubusercontent.com/12253240/72341691-85434880-36d3-11ea-80dc-0c026c7ac5b8.png)
that one in blue should then update to the latest the one in debug doesn't matter and wont run at all 

Reinstall the application and run the shortcut from our desktop when it asks for an update just say run and install

**Comment by Abben86** [comment]
I tried that, exactly like you said. After updating, 
the app opens up a blank window called "messagebox"  then shuts down immediately.  I tried taking a screenshot with my computer but the box didnt show up when i pasted in paint (??). So i took a pic with my cell and uploaded it, really weird. :\

![messagebox](https://user-images.githubusercontent.com/59807924/72343863-2cbe7c00-36d0-11ea-9f79-ca1dd5543db4.jpg)

**Comment by xXxTheDarkprogramerxXx** [comment]
I actually have no idea why your having these issues.....
Since there is no errors I can't actually tell you whats going on 
Could you try and grab a screenshot of your event viewer ?
Start app ps2 classics let it crash and start event viewer 
Navigate to applications in event viewer in windows logs and see if you can find the error relating to ps2 classics 
![image](https://user-images.githubusercontent.com/12253240/72494588-082be680-382d-11ea-8ccf-88c255f9e407.png)

**Comment by Abben86** [comment]
Ok! This is what came up in event viewer.
Thanks


![event1](https://user-images.githubusercontent.com/59807924/72509826-a5484880-3848-11ea-93ac-638a24318824.jpg)
![event2](https://user-images.githubusercontent.com/59807924/72509833-a7aaa280-3848-11ea-8bf2-b8cbc10f0431.jpg)
![event3](https://user-images.githubusercontent.com/59807924/72509837-aaa59300-3848-11ea-9fdd-930cf9723dd4.jpg)

**Comment by xXxTheDarkprogramerxXx** [comment]
Does you computer not have a soundcard ?

**Comment by Abben86** [comment]
I tried re-installing my audio drivers and suddenly the app started working! :) Thanks for your help
