### ISSUE TITLE
Open/Save/Settings entries doesn't work

### ISSUE THREAD

**Issue by RiotArchiveProject** [xXxTheDarkprogramerxXx/PS3Tools#4]
All options under the "File" tab appear to not work except for issue submission and credits.

Additionally I do not see any way to change the passcode that is used for packaging. Having this option would be nice as well.

**Comment by xXxTheDarkprogramerxXx** [comment]
I would like to keep the passcode the same so that if oneday we need to extract the iso for some reason or get something from the file its possible with one easy click 

Also the file tab as i said in twitter was for show untill the next releaee its just some of the things i'm planing on releasing with this tool :P

Thanks for your support and your feedback 
P.S. if i do end up adding a method of changing the password on the pkg's i would most probabbly add it as a setting

**Comment by RiotArchiveProject** [comment]
If thats the case make the passcode `00000000000000000000000000000000` as the default as I had (aggressively) suggested when PKGs were first starting to show up.
I also don't follow you on twitter so I didn't see these tweets. Thanks for letting me know though.

In the future if you have options for modifying the config for each title do let me know as there's some titles that dont work and I'm interested in looking into them.

Additionally, some instances of games have come in CUE/BIN format and so far I have yet to successfully boot such games that were ripped in this format even after converting them. I will continue to try though. If you look into this as well it might be worth it.
